import {
  HomeOutlined as HomeIcon,
  UserAddOutlined as NewUserIcon,
  TeamOutlined as AllUsersIcon,
  SmileOutlined as SmileFaceIcon,
  UsergroupAddOutlined as FollowingIcon,
  MessageOutlined as MessageIcon,
  MessageFilled as MessageIconFilled,
  FileTextOutlined as PostsIcons,
  SettingOutlined as SettingsIcon,
  LogoutOutlined as LogoutIcon,
  SearchOutlined as SearchIcon,
  CloseCircleOutlined as CloseIcon,
  CloseOutlined as CloseXIcon,
  PhoneOutlined as PhoneIcon,
  MailOutlined as EmailIcon,
  MailFilled as EmailIconFilled,
  LikeOutlined as LikeIcon,
  LikeFilled as LikeIconFilled,
  CommentOutlined as CommentIcon,
  ShareAltOutlined as ShareIcon,
  SendOutlined as SendIcon,
  CameraOutlined as CameraIcon,
  VideoCameraOutlined as VideoIcon,
  PictureOutlined as PictureIcon,
  EnvironmentOutlined as MapIcon,
  UpCircleOutlined as GoUpButtonIcon,
  LinkedinFilled as LinkedInIcon,
  InstagramFilled as InstagramIcon,
  TwitterCircleFilled as TwitterIcon,
  MenuOutlined as MobileMenuIcon,
  EditOutlined as EditIcon,
  SlidersOutlined as ChangeTheme,
} from "@ant-design/icons";

export {
  HomeIcon,
  NewUserIcon,
  AllUsersIcon,
  SmileFaceIcon,
  FollowingIcon,
  MessageIcon,
  MessageIconFilled,
  SettingsIcon,
  LogoutIcon,
  SearchIcon,
  CloseIcon,
  CloseXIcon,
  PhoneIcon,
  EmailIcon,
  EmailIconFilled,
  LikeIcon,
  LikeIconFilled,
  CommentIcon,
  PostsIcons,
  ShareIcon,
  SendIcon,
  CameraIcon,
  VideoIcon,
  PictureIcon,
  MapIcon,
  GoUpButtonIcon,
  LinkedInIcon,
  InstagramIcon,
  TwitterIcon,
  MobileMenuIcon,
  EditIcon,
  ChangeTheme,
};
