import {
  HomeOutlined as HomeIcon,
  UserAddOutlined as NewUserIcon,
  TeamOutlined as AllUsersIcon,
  MessageOutlined as MessageIcon,
  SettingOutlined as SettingsIcon,
  LogoutOutlined as LogoutIcon,
  SearchOutlined as SearchIcon,
  CloseCircleOutlined as CloseIcon,
  PhoneOutlined as PhoneIcon,
  MailOutlined as EmailIcon,
  LikeOutlined as LikeIcon,
  LikeFilled as LikeIconFilled,
  CommentOutlined as CommentIcon,
  ShareAltOutlined as ShareIcon,
  SendOutlined as SendIcon,
  CameraOutlined as CameraIcon,
  VideoCameraOutlined as VideoIcon,
  PictureOutlined as PictureIcon,
  EnvironmentOutlined as MapIcon,
  UpCircleOutlined as GoUpButtonIcon,
} from "@ant-design/icons";

export {
  HomeIcon,
  NewUserIcon,
  AllUsersIcon,
  MessageIcon,
  SettingsIcon,
  LogoutIcon,
  SearchIcon,
  CloseIcon,
  PhoneIcon,
  EmailIcon,
  LikeIcon,
  LikeIconFilled,
  CommentIcon,
  ShareIcon,
  SendIcon,
  CameraIcon,
  VideoIcon,
  PictureIcon,
  MapIcon,
  GoUpButtonIcon,
};
